version: '3.9'
services:
  app:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: sh -c "npm install && npm start"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: