const VALIDATION_ERROR = "Validation error: ";
const PAGE_INDEX_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_ONE = "pageIndex should be greater than or equal to 1";
const PAGE_SIZE_LIMIT = "pageSize limit: ";
const DEFAULT_PAGE_SIZE_LIMIT = 100;
const VIDEOS_NOT_FOUND = "Videos not found";
const EXCEPTION_IN_FETCHING_VIDEOS = "Exception in fetching videos";
const DEFAULT_PAGE_INDEX = 1;
const DEFAULT_PAGE_SIZE = 50;

module.exports = {VALIDATION_ERROR, PAGE_INDEX_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_ONE, PAGE_SIZE_LIMIT, DEFAULT_PAGE_SIZE_LIMIT, VIDEOS_NOT_FOUND, EXCEPTION_IN_FETCHING_VIDEOS, DEFAULT_PAGE_INDEX, DEFAULT_PAGE_SIZE};